# Generated by Django 6.0.6 on 2026-07-16 16:16

import apps.profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_backfill_existing_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[apps.profiles.models.validate_past_date]),
        ),
    ]
