# Generated by Django 6.0.6 on 2026-07-02 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time when this record was last updated.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indicates whether this record has been soft deleted.')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='The date and time when this record was soft deleted.', null=True)),
                ('title', models.CharField(help_text='The title of the blog post.', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly unique identifier for the post.', max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Optional short summary of the blog post.')),
                ('content', models.TextField(help_text='Main content of the blog post.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', help_text='Current publication status of the post.', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='The date and time when the post was published.', null=True)),
                ('author', models.ForeignKey(help_text='The user who owns this post.', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='The user who soft deleted this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-published_at', '-created_at'),
                'indexes': [models.Index(fields=['status'], name='posts_post_status_79fb4e_idx'), models.Index(fields=['published_at'], name='posts_post_publish_04eb5b_idx'), models.Index(fields=['author'], name='posts_post_author__19d68b_idx')],
            },
        ),
    ]
