# Generated by Django 6.0.6 on 2026-07-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categories used to organize this post.', related_name='posts', to='categories.category'),
        ),
    ]
