# Generated by Django 6.0.6 on 2026-07-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_categories"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Tags used to organize this post.",
                related_name="posts",
                to="tags.tag",
            ),
        ),
    ]
