# Generated by Django 6.0.6 on 2026-07-29 05:01

import apps.posts.upload_paths
import apps.posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_post_search_vector_gin"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional featured image displayed with the blog post.",
                upload_to=apps.posts.upload_paths.post_featured_image_upload_path,
                validators=[apps.posts.validators.validate_post_featured_image],
            ),
        ),
    ]
