# Generated by Django 6.0.6 on 2026-08-03 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_at', '-created_at', '-pk'), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
